- hosts: localhost
  pre_tasks:
    - name: Update packages
      become: true
      pacman:
        update_cache: true
      when: ansible_facts["os_family"] == "Archlinux"
      tags:
        - ssh
        - dotfiles
        - zsh
        - dev-tools
        - dev
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include_tasks:
        file: tasks/ssh.yml
      tags:
        - ssh
        - dev
    - include_tasks:
        file: tasks/dev-tools.yml
      tags:
        - dotfiles
        - dev
    - include_tasks:
        file: tasks/zsh.yml
      tags:
        - zsh
        - dev
    - include_tasks:
        file: tasks/dev-dotfiles.yml
      tags:
        - dotfiles
        - dev

