- hosts: localhost
  become: true
  pre_tasks:
    - name: Update apt
      apt:
        force_apt_get: yes
        update_cache: yes
        state: present
      tags:
        - node
        - zsh
        - ssh
        - dotfiles
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include_tasks: tasks/zsh.yml
      tags:
        - zsh
    - include_tasks: tasks/node.yml
      tags:
        - node
    - include_tasks: tasks/ssh.yml
      tags:
        - ssh
        - dotfiles
        - install
    - include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - install
    