- hosts: localhost
  # become: true
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: yes
        update_cache: yes
        state: present
      tags:
        - node
        - zsh
        - ssh
        - docker
        - dotfiles
        - productivity
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include_tasks:
        file: tasks/zsh.yml
      tags:
        - zsh
    - include_tasks:
        file: tasks/node.yml
      tags:
        - node
    - include_tasks:
        file: tasks/productivity-tools.yml
      tags:
        - productivity
        - install
    - include_tasks:
        file: tasks/ssh.yml
      tags:
        - ssh
        - dotfiles
        - install
    - include_tasks:
        file: tasks/dotfiles.yml
      tags:
        - dotfiles
        - install
    - include_tasks:
        file: tasks/nvim-setup.yml
      tags:
        - install
        - nvim
        - neovim
    - include_tasks:
        file: tasks/docker.yml
      tags:
        - docker
        - install
    - include_tasks:
        file: tasks/font.yml
      tags:
        - font
        - install
