- hosts: localhost
  become: true
  pre_tasks:
    - name: Update apt
      apt:
        force_apt_get: yes
        update_cache: yes
        state: present
      tags:
        - node
        - zsh
        - ssh
        - docker
        - dotfiles
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include_tasks: 
        file: tasks/zsh.yml
        apply:
          tags:
            - zsh
    - include_tasks: 
        file: tasks/node.yml
        apply:
          tags:
            - node
    - include_tasks: 
        file: tasks/ssh.yml
        apply:
          tags:
            - ssh
            - dotfiles
            - install
    - include_tasks: 
        file: tasks/dotfiles.yml
        apply:
          tags:
            - dotfiles
            - install
    - include_tasks:
        file: tasks/docker.yml
        apply:
          tags:
            - docker
            - install