- name: Cloning dev dotfiles
  ansible.builtin.git:
    repo: git@github.com:pinnheads/.dev.git
    dest: "{{ lookup('env', 'HOME') }}/.dev"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - dev-dotfiles
    - dev

- name: Stow dotfiles
  shell: cd $HOME/.dev && ./stow
  tags:
    - dev-dotfiles
    - dev
