- name: Update apt package index
  apt:
    update_cache: yes
  tags:
    - docker
    - install
- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present
  tags:
    - docker
    - install
- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - docker
    - install
- name: Download Docker's GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags:
    - docker
    - install
- name: Add Docker repository to apt sources
  copy:
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
  tags:
    - docker
    - install
- name: Update apt package index again
  apt:
    update_cache: yes
  tags:
    - docker
    - install
- name: Install Docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags:
    - docker
    - install
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags:
    - docker
    - install
- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
    - install