- name: Install required packages
  become: true
  pacman:
    name: [
      "git",
      "make",
      "unzip",
      "gcc",
      "ripgrep",
      "fd",
      "tree-sitter-cli",
      "lazygit",
      "nodejs",
      "lua",
      "luarocks",
      "npm",
      "python-pip",
      "openssh",
      "neovim",
      "tmux",
      "ttf-jetbrains-mono"
    ]
  when: ansible_facts["os_family"] == "Archlinux"
  tags:
    - neovim
    - dev

- name: Refresh font cache
  ansible.builtin.command: fc-cache -v
  changed_when: false
  failed_when: false
  tags:
    - neovim
    - dev

- name: Copy the config for neovim
  ansible.builtin.git:
    repo: git@github.com:pinnheads/neovim.git
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - neovim
    - dev
