- name: Install zsh
  become: true
  apt:
    name: [ "zsh", "curl" ]
  tags:
    - zsh
- name: Set zsh as default shell
  become: true
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Remove oh-my-zsh folder if it is present
  file:
    path: ~/.oh-my-zsh
    state: absent
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh
- name: Check if ~/.zshrc file is present
  ansible.builtin.stat:
    path: "{{ansible_env.HOME}}/.zshrc"
  register: zshrc_file
- name: Remove the original .zshrc file
  file:
    path: "{{ansible_env.HOME}}/.zshrc"
    state: absent
  when: zshrc_file.stat.exists
  tags:
    - zsh
- name: Check if ~/.bashrc file is present
  ansible.builtin.stat:
    path: "{{ansible_env.HOME}}/.bashrc"
  register: bashrc_file
- name: Remove the original .bashrc file
  file:
    path: "{{ansible_env.HOME}}/.bashrc"
    state: absent
  when: bashrc_file.stat.exists
  tags:
    - zsh
