- name: Install zsh
  become: true
  apt:
    name: zsh
  tags:
    - zsh
- name: Set zsh as default shell
  become: true
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Remove oh-my-zsh folder if it is present
  file:
    path: ~/.oh-my-zsh
    state: absent
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh
- name: Check if .zshrc file exists
  stat:
    path: ~/.zshrc
  register: zshrc_file
  tags:
    - zsh
- name: Backup existing .zshrc file
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc.bak
  tags:
    - zsh
- name: Check if bashrc file exists
  stat:
    path: ~/.bashrc
  register: zshrc_file
  tags:
    - zsh
- name: Backup existing .bashrc file
  copy:
    src: ~/.bashrc
    dest: ~/.bashrc.bak
  tags:
    - zsh
  when: zshrc_file.stat.exists
- name: Remove the original .zshrc file
  file:
    path: ~/.zshrc
    state: absent
  tags:
    - zsh
