- name: Install zsh
  apt:
    name: zsh
  tags:
    - zsh
- name: Set zsh as default shell
  shell: chsh -s `which zsh`
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh
- name: Check if .zshrc file exists
  stat:
    path: ~/.zshrc
  register: zshrc_file
- name: Backup existing .zshrc file
  copy:
    src: ~/.zshrc
    dest: ~/.zshrc.backup
  when: zshrc_file.stat.exists